name: components
description: A new Flutter project, which all components located
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^7.4.0
  flutter_bloc: ^8.1.3
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.5
  formz: ^0.6.0
  connectivity_plus: ^4.0.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true