name: components
description: A new Flutter project, which all components located
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^8.0.1
  keyboard_dismisser: ^3.0.0
  formz: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  intl: ^0.19.0
  torch_light: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true