name: components
description: A new Flutter project, which all components located
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1
  formz: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  torch_light: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true